utils/urls.py
from django.urls import path

from . import views

app_name = "utilities"

urlpatterns = [
    path('md_preview/', views.MarkdownPreview.as_view(), name='preview'),
    path('md_preview_safe/', views.MarkdownPreviewSafe.as_view(), name='preview_safe'),
    path('md_preview_newsletter/', views.MarkdownPreviewNewsletter.as_view(), name='preview_newsletter'),
    path('md_preview_text/', views.MarkdownPreviewText.as_view(), name='preview_text'),
]

votes/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import ApprovalVoteView, DoneView, ApprovalResultView, HomeView, VoteView, FPTPResultView, FPTPVoteView, \
    STVVoteView, STVResultView, STVAllVoteView, UpdateElection, CreateElection, CreateCandidate, UpdateCandidate, AdminView, TicketView, ResultView

app_name = "votes"

urlpatterns = [
    path('', HomeView.as_view(), name="elections"),
    path('<int:election>/', VoteView.as_view(), name="vote"),
    path('<int:election>/approval/', ApprovalVoteView.as_view(), name="approval_vote"),
    path('<int:election>/fptp/', FPTPVoteView.as_view(), name="fptp_vote"),
    path('<int:election>/stv/', STVVoteView.as_view(), name="stv_vote"),
    path('<int:election>/<uuid:slug>/', DoneView.as_view(), name="vote_done"),
    path('<int:election>/results/', ResultView.as_view(), name="results"),
    path('<int:election>/results/approval/', ApprovalResultView.as_view(), name="approval_results"),
    path('<int:election>/results/fptp/', FPTPResultView.as_view(), name="fptp_results"),
    path('<int:election>/results/stv/', STVResultView.as_view(), name="stv_results"),
    path('<int:election>/results/stv/votes/', STVAllVoteView.as_view(), name="stv_all_votes"),
    path('admin/', AdminView.as_view(), name="admin"),
    path('admin/tickets/', TicketView.as_view(), name="tickets"),
    path('admin/create/', CreateElection.as_view(), name="create_election"),
    path('admin/edit/<int:election>/', UpdateElection.as_view(), name="update_election"),
    path('admin/edit/<int:election>/create/', CreateCandidate.as_view(), name="create_candidate"),
    path('admin/edit/<int:election>/edit/<int:candidate>/', UpdateCandidate.as_view(), name="update_candidate"),
]

votes/models.py
import uuid as uuid
from django.db import models


# Create your models here.
class Election(models.Model):
    class Types(models.IntegerChoices):
        FPTP = 0, "First past the post"
        APRV = 1, "Approval vote"
        STV = 2, "Single Transferable Vote"

    name = models.CharField(max_length=50)
    description = models.TextField()
    vote_type = models.IntegerField(choices=Types.choices, default=Types.FPTP)
    max_votes = models.IntegerField(default=2,
                                    help_text="Ignored except in Plurality. Number of candidates selectable per vote")
    seats = models.IntegerField(default=1, help_text="Ignored except in STV. Number of people who can win")
    open = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def votes(self):
        if self.vote_type == Election.Types.FPTP:
            return self.fptpvote_set.all()
        elif self.vote_type == Election.Types.APRV:
            return self.aprvvote_set.all()
        elif self.vote_type == Election.Types.STV:
            return self.stvvote_set.all()
        else:
            raise NotImplemented()

    class Meta:
        ordering = ('id',)


class Candidate(models.Model):
    class State(models.IntegerChoices):
        STANDING = 0, "Standing"
        WITHDRAWN = 1, "Withdrawn"

    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    state = models.IntegerField(choices=State.choices, default=State.STANDING)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def formid(self):
        return "option_" + str(self.election.id) + "_" + str(self.id)

    def votes(self):
        return self.election.votes().filter(selection=self.id)


class Ticket(models.Model):
    member = models.CharField(max_length=20)
    uuid = models.UUIDField(editable=False, default=uuid.uuid4, unique=True)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    spent = models.BooleanField(default=False)

    def __str__(self):
        return str(self.uuid)

    class Meta:
        unique_together = (('member', 'election'),)


class Vote(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    uuid = models.UUIDField(unique=True)
    time = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.uuid)


class FPTPVote(Vote):
    selection = models.ForeignKey(Candidate, models.CASCADE)


class APRVVote(Vote):
    selection = models.ManyToManyField(Candidate)


class STVVote(Vote):
    selection = models.ManyToManyField(Candidate, through='STVPreference')


class STVPreference(models.Model):
    order = models.IntegerField()
    stvvote = models.ForeignKey(STVVote, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order']


class STVResult(models.Model):
    election = models.OneToOneField(Election, on_delete=models.CASCADE)
    full_log = models.TextField()
    winners = models.ManyToManyField(Candidate)
    generated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.election)

votes/forms.py
from django.forms import Form, ModelForm, Textarea, ModelMultipleChoiceField, CharField
from django.urls import reverse_lazy

from .models import Election, Candidate

MD_INPUT_SAFE = {
    'class': 'markdown-input',
    'data-endpoint': reverse_lazy('utilities:preview_safe'),
}

MD_INPUT_TEXT = {
    'class': 'markdown-input',
    'data-endpoint': reverse_lazy('utilities:preview_safe'),
}


class ElectionForm(ModelForm):
    class Meta:
        model = Election
        fields = ['name', 'description', 'vote_type', 'max_votes', 'seats', 'open']
        widgets = {'description': Textarea(attrs=MD_INPUT_SAFE)}


class CandidateForm(ModelForm):
    class Meta:
        model = Candidate
        fields = ['name', 'description', 'state']
        widgets = {'description': Textarea(attrs=MD_INPUT_TEXT)}


class DateTicketForm(Form):
    ids = CharField(help_text="A list of whitespace separated uni-ids", widget=Textarea(), label="IDs")
    elections = ModelMultipleChoiceField(Election.objects.all())

votes/views.py
import random
from operator import itemgetter, attrgetter

from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, RedirectView, CreateView, UpdateView, \
    FormView
from django.shortcuts import get_object_or_404, HttpResponseRedirect, reverse

from uwcsvote.permissions import PERMS
from .forms import ElectionForm, CandidateForm, DateTicketForm
from .models import Election, STVVote, STVPreference, FPTPVote, APRVVote, Candidate, Ticket, Vote, STVResult
from .stv import Election as StvCalculator


# Create your views here.
class HomeView(LoginRequiredMixin, ListView):
    template_name = "votes/home.html"
    model = Election
    context_object_name = "elections"

    def get_queryset(self):
        tickets = self.request.user.member.ticket_set.filter(spent=False)
        return Election.objects.filter(ticket__in=tickets, open=True)


class AdminView(PermissionRequiredMixin, ListView):
    template_name = "votes/admin.html"
    permission_required = PERMS.votes.view_election
    model = Election
    context_object_name = "elections"

    def get_queryset(self):
        return Election.objects.filter(archived=False)


class TicketView(PermissionRequiredMixin, FormView):
    permission_required = PERMS.votes.add_ticket
    form_class = DateTicketForm
    template_name = "votes/tickets.html"
    success_url = reverse_lazy('votes:admin')

    def form_valid(self, form):

        for uniid in form.cleaned_data['ids'].split():
            for election in form.cleaned_data['elections']:
                Ticket.objects.get_or_create(member=uniid, election=election)
        return super().form_valid(form)


class CreateElection(PermissionRequiredMixin, CreateView):
    model = Election
    permission_required = PERMS.votes.add_election
    template_name = "votes/create_election.html"
    form_class = ElectionForm

    def get_success_url(self):
        return reverse("votes:admin")


class UpdateElection(PermissionRequiredMixin, UpdateView):
    model = Election
    permission_required = PERMS.votes.change_election
    template_name = "votes/create_election.html"
    form_class = ElectionForm
    pk_url_kwarg = "election"

    def get_success_url(self):
        return reverse("votes:admin")


class CreateCandidate(PermissionRequiredMixin, CreateView):
    model = Candidate
    permission_required = PERMS.votes.add_candidate
    template_name = "votes/create_candidate.html"
    form_class = CandidateForm

    def get_success_url(self):
        return reverse("votes:update_election", args=[self.kwargs['election']])

    def form_valid(self, form):
        form.instance.election = get_object_or_404(Election, id=self.kwargs['election'])
        return super().form_valid(form)


class UpdateCandidate(PermissionRequiredMixin, UpdateView):
    model = Candidate
    permission_required = PERMS.votes.change_candidate
    template_name = "votes/create_candidate.html"
    form_class = CandidateForm
    pk_url_kwarg = "candidate"

    def get_success_url(self):
        return reverse("votes:update_election", args=[self.kwargs['election']])

    def get_queryset(self):
        return Candidate.objects.filter(election_id=self.kwargs['election'])


class DoneView(LoginRequiredMixin, DetailView):
    model = Vote
    slug_field = "uuid"

    def get_template_names(self):
        if self.election.vote_type == Election.Types.APRV:
            return "votes/approval_done.html"
        elif self.election.vote_type == Election.Types.FPTP:
            return "votes/fptp_done.html"
        elif self.election.vote_type == Election.Types.STV:
            return "votes/stv_done.html"

    def get_queryset(self):
        self.election = get_object_or_404(Election, id=self.kwargs['election'])
        return self.election.votes()


class VoteView(LoginRequiredMixin, RedirectView):
    def get_object(self):
        return get_object_or_404(Election, id=self.kwargs['election'])

    def get_redirect_url(self, *args, **kwargs):
        election = self.get_object()
        if election.vote_type == Election.Types.APRV:
            return reverse('votes:approval_vote', args=[self.kwargs['election']])
        elif election.vote_type == Election.Types.FPTP:
            return reverse('votes:fptp_vote', args=[self.kwargs['election']])
        elif election.vote_type == Election.Types.STV:
            return reverse('votes:stv_vote', args=[self.kwargs['election']])
        else:
            raise NotImplementedError()


class ResultView(PermissionRequiredMixin, RedirectView):
    permission_required = PERMS.votes.view_election

    def get_object(self):
        return get_object_or_404(Election, id=self.kwargs['election'])

    def get_redirect_url(self, *args, **kwargs):
        election = self.get_object()
        if election.vote_type == Election.Types.APRV:
            return reverse('votes:approval_results', args=[self.kwargs['election']])
        elif election.vote_type == Election.Types.FPTP:
            return reverse('votes:fptp_results', args=[self.kwargs['election']])
        elif election.vote_type == Election.Types.STV:
            return reverse('votes:stv_results', args=[self.kwargs['election']])
        else:
            raise NotImplementedError()


class ApprovalResultView(PermissionRequiredMixin, ListView):
    model = Candidate
    permission_required = PERMS.votes.view_aprvvote
    template_name = "votes/approval_results.html"
    ordering = [Count("aprvvotes_set")]
    context_object_name = "choices"

    def get_queryset(self):
        self.election = get_object_or_404(Election, id=self.kwargs['election'], vote_type=Election.Types.APRV,
                                          open=False)
        return self.election.candidate_set.all()

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        ctxt['election'] = self.election
        ctxt['choices'] = sorted(ctxt['choices'], key=lambda x: -x.votes().count())
        return ctxt


class ApprovalVoteView(UserPassesTestMixin, TemplateView):
    template_name = "votes/approval_votescreen.html"

    def test_func(self):
        if self.request.user.is_anonymous:
            return False
        self.election = get_object_or_404(Election, id=self.kwargs['election'], open=True,
                                          vote_type=Election.Types.APRV)
        return self.request.user.member.ticket_set.filter(election=self.election, spent=False).exists()

    def post(self, request, **kwargs):
        self.get_context_data(**kwargs)
        ticket = get_object_or_404(request.user.member.ticket_set.all(), election=self.election, spent=False)
        print(request.POST)
        errors = []
        if "selection" not in request.POST:
            errors.append("Please select at least one option")
            selection = []
        else:
            selection = request.POST.getlist("selection")
        if 0 < self.election.max_votes < len(selection):
            errors.append("Too many options selected")
        try:
            selection = [int(s) for s in selection]
        except ValueError:
            errors.append("Invalid option submitted")
        allowed = [a.id for a in self.election.candidate_set.all()]
        for i in selection:
            if i not in allowed:
                errors.append("Unknown option selected")

        if errors:
            return self.get(request, errors=errors)
        else:
            vote = APRVVote(
                uuid=ticket.uuid,
                election=self.election,
            )
            vote.save()
            vote.selection.add(*selection)

            ticket.spent = True
            ticket.save()

            return HttpResponseRedirect(
                reverse("votes:vote_done", kwargs={'election': self.election.id, 'slug': vote.uuid}))

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        self.election = get_object_or_404(Election, id=self.kwargs['election'], open=True,
                                          vote_type=Election.Types.APRV)
        ctxt['election'] = self.election
        ctxt['choices'] = list(self.election.candidate_set.all())
        random.shuffle(ctxt['choices'])
        return ctxt


class FPTPResultView(PermissionRequiredMixin, ListView):
    model = Candidate
    permission_required = PERMS.votes.view_fptpvote
    template_name = "votes/fptp_results.html"
    ordering = [Count("fptpvotes_set")]
    context_object_name = "choices"

    def get_queryset(self):
        self.election = get_object_or_404(Election, id=self.kwargs['election'], vote_type=Election.Types.FPTP,
                                          open=False)
        return self.election.candidate_set.all()

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        ctxt['election'] = self.election
        ctxt['choices'] = sorted(ctxt['choices'], key=lambda x: -x.votes().count())
        return ctxt


class FPTPVoteView(UserPassesTestMixin, TemplateView):
    template_name = "votes/fptp_votescreen.html"

    def test_func(self):
        if self.request.user.is_anonymous:
            return False
        self.election = get_object_or_404(Election, id=self.kwargs['election'], open=True,
                                          vote_type=Election.Types.FPTP)
        return self.request.user.member.ticket_set.filter(election=self.election, spent=False).exists()

    def post(self, request, **kwargs):
        self.get_context_data(**kwargs)
        ticket = get_object_or_404(request.user.member.ticket_set.all(), election=self.election, spent=False)
        print(request.POST)
        errors = []
        if "selection" not in request.POST:

votes/templates/votes/admin.html
{% extends 'main.html' %}

{% block title %}Votes{% endblock %}
{% block pagetitle %}Votes{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
{% endblock %}
{% block breadcrumbs_child %}Admin{% endblock %}

{% block leftcontents %}
    {{ block.super }}
    {% if perms.votes.change_elections %}
        <a class="btn btn-block btn-outline-dark mb-3" href="{% url "admin:votes_election_changelist" %}">Edit</a>
    {% endif %}
{% endblock %}

{% block body %}
    <h2>Change</h2>
    <p>
        <a href="{% url "votes:create_election" %}"
           class="btn btn-outline-success btn-block">
            Create New
        </a>
    </p>
    <p>
        <a href="{% url "votes:tickets" %}"
           class="btn btn-outline-success btn-block">
            Issue Tickets
        </a>
    </p>
    <div class="list-group mb-3">
        {% for election in object_list %}
            <a href="{% url "votes:update_election" election.id %}"
               class="list-group-item list-group-item-action">
                {{ election.name }}
            </a>
        {% endfor %}
    </div>
    <h2>Results</h2>
    <div class="list-group">
        {% for election in object_list %}
            {% if election.open %}
            {% else %}
            <a href="{% url "votes:results" election.id %}"
               class="list-group-item list-group-item-action">
                {{ election.name }}
            </a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

votes/templates/votes/approval_done.html
{% extends 'main.html' %}
{% load markdown_tags %}

{% block title %}{{ object.election.name }} - Votes{% endblock %}
{% block pagetitle %}Vote Complete{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
    <li class="breadcrumb-item">{{ object.election.name }}</li>
{% endblock %}
{% block breadcrumbs_child %}Complete{% endblock %}

{% block leftcontents %}
    {{ block.super }}
    {% if perms.votes.change_elections %}
        <a class="btn btn-block btn-outline-dark mb-3" href="{% url "admin:votes_election_changelist" %}">Edit</a>
    {% endif %}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <p class="card-text">Congratulations, your vote has been cast!</p>
            <p><strong>Date/time:</strong> {{ object.time }}</p>
            <h4>Selection{{ object.selection.count|pluralize }}:</h4>
            {% block selection %}
                <ul class="list-group mb-3">
                    {% for i in object.selection.all %}
                        <li class="list-group-item">{{ i.name }}</li>
                    {% endfor %}
                </ul>
            {% endblock %}
            <p class="card-text">Consider bookmarking this page for your personal reference</p>
            <p class="card-text">If anything appears wrong, please contact the returning officer immediately, with the
                following uuid:
                <br>
                <code>{{ object.uuid }}</code>
            </p>
            <a class="btn btn-large btn-block btn-primary" href="{% url 'votes:elections' %}">Return to list of elections</a>
        </div>
    </div>
{% endblock %}

votes/templates/votes/approval_votescreen.html
{% extends 'main.html' %}
{% load markdown_tags %}

{% block title %}{{ election.name }} - Votes{% endblock %}
{% block pagetitle %}{{ election.name }}{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
{% endblock %}
{% block breadcrumbs_child %}{{ election.name }}{% endblock %}

{% block leftcontents %}
    {{ block.super }}
    {% if perms.votes.change_elections %}
        <a class="btn btn-block btn-outline-dark mb-3" href="{% url "admin:votes_election_changelist" %}">Edit</a>
    {% endif %}
{% endblock %}

{% block body %}
    <div class="modal fade" id="voteModal" tabindex="-1" aria-labelledby="voteModalTitle" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="voteModalTitle">Submit Vote</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        You will not be able to change your vote after this point
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-outline-success" form="voteform">Submit</button>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% if election.description %}
                <div class="mb-3">
                    {{ election.description|parse_md_safe }}
                </div>
            {% endif %}
            {% block alerts %}
                {% if election.max_votes != 0 %}
                    {% if election.max_votes == 1 %}
                        <div class="alert alert-primary">Please select a single option.</div>
                    {% else %}
                        <div class="alert alert-primary">Please select up to {{ election.max_votes }} options.</div>
                    {% endif %}
                {% endif %}
            {% endblock %}
            {% if errors %}
                {% for e in errors %}
                    <div class="alert alert-danger">{{ e }}</div>
                {% endfor %}
            {% endif %}
            <form method="post" id="voteform">
                {% csrf_token %}
                {% for choice in choices %}
                    {% block voteelement %}
                        <input type="checkbox" class="d-none" name="selection"
                               id="{{ choice.formid }}"
                               value="{{ choice.id }}">
                    {% endblock %}
                    <div class="card vote-option mb-3">
                        <label class="mb-0 card-header" for="{{ choice.formid }}" class="">
                            {{ choice.name }}
                        </label>
                        {% if choice.description|parse_md_safe %}
                            <div class="card-body markdown-text">
                                {{ choice.description|parse_md_safe }}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </form>
            <button class="btn-outline-primary btn-block btn" data-toggle="modal" data-target="#voteModal">Submit Vote</button>
        </div>
    </div>
{% endblock %}

votes/templates/votes/create_candidate.html
{% extends 'main.html' %}
{% load markdown_tags %}

{% block title %}Edit - Votes{% endblock %}
{% block pagetitle %}{% if object %}Edit{% else %}Create{% endif %} Election{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
    <li class="breadcrumb-item"><a href="{% url 'votes:admin' %}">Admin</a></li>
    {% if object %}
        <li class="breadcrumb-item">{{ object.election.name }}</li>
        <li class="breadcrumb-item">{{ object.name }}</li>
    {% else %}
    {% endif %}
{% endblock %}
{% block breadcrumbs_child %}{% if object %}Edit{% else %}Create{% endif %}{% endblock %}

{% block body %}
    {% include "parts/render_form.html" %}
{% endblock %}

votes/templates/votes/create_election.html
{% extends 'main.html' %}
{% load markdown_tags %}

{% block title %}Edit - Votes{% endblock %}
{% block pagetitle %}{% if object %}Edit{% else %}Create{% endif %} Election{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
    <li class="breadcrumb-item"><a href="{% url 'votes:admin' %}">Admin</a></li>
    {% if object %}
        <li class="breadcrumb-item">{{ object.name }}</li>
    {% else %}
    {% endif %}
{% endblock %}
{% block breadcrumbs_child %}{% if object %}Edit{% else %}Create{% endif %}{% endblock %}

{% block body %}
    {% include "parts/render_form.html" %}

    {% if object %}
        <h2>Candidates</h2>
        <p>
            <a href="{% url "votes:create_candidate" election.id %}"
               class="btn btn-outline-success btn-block">
                Create New
            </a>
        </p>
        {% for candidate in object.candidate_set.all %}
            <div class="card  mt-3">
                <h3 class="card-header">
                    {{ candidate.name }}
                </h3>
                {% if candidate.description %}
                    <div class="card-body markdown-text">
                        {{ candidate.description|parse_md_safe }}
                    </div>
                {% endif %}
                <div class="card-footer">
                    <p class="btn-group">
                        <a class="btn btn-outline-primary"
                           href="{% url "votes:update_candidate" object.id candidate.id %}">
                            <i class="fas fa-edit"></i><span class="sr-only">Edit Candidate</span>
                        </a>
                        <a class="btn btn-outline-danger"
                           href="{% url "votes:update_candidate" object.id candidate.id %}">
                            <i class="fas fa-trash-alt"></i><span class="sr-only">Delete Candidate</span>
                        </a>
                    </p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

votes/templates/votes/home.html
{% extends 'main.html' %}

{% block title %}Votes{% endblock %}
{% block pagetitle %}Votes{% endblock %}

{% block breadcrumbs_child %}Votes{% endblock %}

{% block leftcontents %}
    {{ block.super }}
    {% if perms.votes.change_elections %}
        <a class="btn btn-block btn-outline-dark mb-3" href="{% url "admin:votes_election_changelist" %}">Edit</a>
    {% endif %}
{% endblock %}

{% block body %}
    {% if perms.votes.change_elections %}
    <p>
        <a href="{% url "votes:admin" %}"
           class="btn btn-outline-warning btn-block">
            Admin
        </a>
    </p>
    {% endif %}
    <div class="list-group">
        {% for election in object_list %}
            <a href="{% url "votes:vote" election.id %}"
               class="list-group-item list-group-item-action">
                {{ election.name }}
            </a>
        {% empty %}
            <div class="list-group-item text-muted">No elections currently available. Please check back later.</div>
        {% endfor %}
    </div>
{% endblock %}

votes/templates/votes/stv_done.html
{% extends 'votes/approval_done.html' %}
{% block selection %}
    <p class="text-muted">Lower number is higher preference (think podium places or top ten lists)</p>
    <ul class="list-group mb-3">
        {% for i in object.stvpreference_set.all %}
            <li class="list-group-item"><span
                    class="badge badge-primary rounded-pill px-2 mr-2">{{ i.order }}</span>{{ i.candidate.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

votes/templates/votes/stv_results.html
{% extends "votes/approval_results.html" %}
{% block results %}
    <h2>Total Turnout: {{ election.stvvote_set.count }}</h2>
    <h2>Available seats: {{ election.seats }}</h2>
    <h2>Winner{{ result.winners.all|pluralize }}</h2>
    <div class="list-group">
        {% for winner in result.winners.all %}
            <div class="list-group-item mb-3">
                {{ winner.name }}
            </div>
        {% endfor %}
    </div>
    <pre>{{ result.full_log }}</pre>
    <p>
        <a class="btn btn-block btn-outline-dark" href="{% url "votes:stv_all_votes" election.id %}">See Votes</a>
    </p>
{% endblock %}

votes/templates/votes/stv_vote_list.html
{% extends 'main.html' %}
{% load markdown_tags %}

{% block title %}{{ election.name }} - Votes{% endblock %}
{% block pagetitle %}{{ election.name }}{% endblock %}

{% block breadcrumbs_parents %}
    <li class="breadcrumb-item"><a href="{% url 'votes:elections' %}">Votes</a></li>
    <li class="breadcrumb-item"><a href="{% url 'votes:admin' %}">Admin</a></li>
    <li class="breadcrumb-item"><a href="{% url 'votes:stv_results' election.id %}">{{ election.name }}</a></li>
{% endblock %}
{% block breadcrumbs_child %}All Votes{% endblock %}

{% block leftcontents %}
    {{ block.super }}
    {% if perms.votes.change_elections %}
        <a class="btn btn-block btn-outline-dark mb-3" href="{% url "admin:votes_election_changelist" %}">Edit</a>
    {% endif %}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <div class="d-flex flex-wrap">
                {% for vote in election.stvvote_set.all %}
                    <div class="card m-1">
                        <div class="card-body">
                            <ol class="list-group">
                                {% for pref in vote.stvpreference_set.all %}
                                    <li class="list-group-item">{{ pref.candidate.name }}</li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}